FROM oven/bun:1 AS base

WORKDIR /app

COPY package.json bun.lock ./

RUN bun install --registry=https://npm.devneeds.ir/

COPY . .

USER bun
EXPOSE 88/tcp
ENTRYPOINT [ "bun", "run", "start:internal" ]
