FROM docker.devneeds.ir/oven/bun:1 AS base

WORKDIR /app

COPY package.json bun.lock ./

RUN bun install --frozen-lockfile

COPY . .

USER bun
EXPOSE 6701/tcp
ENTRYPOINT [ "bun", "run", "start:internal" ]
